version: '3.8'
​
services:
  web:
    image: izmdi/foodgram:latest
    container_name: web
    volumes:
      - static_data:/code/static/
      - nginx_config:/code/nginx/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
​
  db:
    image: postgres:13.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
​
  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - static_data:/code/static/
      - media_data:/code/media/
      - nginx_config:/etc/nginx/conf.d
    restart: always
    depends_on:
      - web
​
volumes:
  postgres_data:
  static_data:
  media_data:
  nginx_config: