version: '3.8'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
  web:
    image: izmdi/foodgram:latest
    volumes:
      - ./static:/var/nginx/static/
      - ./media:/var/nginx/media/
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19
    ports:
      - "80:80"
    volumes:
      - ./static:/var/nginx/static/
      - ./media:/var/nginx/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - web