version: "3.3"

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.2
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
  web:
    image: izmdi/foodgram:latest
    container_name: web
    restart: always
    volumes:
      - static:/code/static/
      - media:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - media:/code/media/
      - static:/code/static/
    depends_on:
      - web