# Generated by Django 3.1.7 on 2021-03-27 19:22

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210324_1236'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoplist',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('recipe')), name='Обнаружено дублирование'),
        ),
        migrations.AddConstraint(
            model_name='shoplist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='shoplist_unique'),
        ),
    ]
