# Generated by Django 3.1.7 on 2021-03-28 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210327_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientamount',
            name='amount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Количество не может быть отрицательным'), django.core.validators.MaxValueValidator(10000, 'А куда вам столько?')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Время приготовления не может быть отрицательным'), django.core.validators.MaxValueValidator(43260, 'Вы собрались готовить это дольше месяца?')]),
        ),
    ]
