name: Foodgram

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 .

  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          push: true
          tags: izmdi/foodgram:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    if: github.ref == 'refs/heads/master'
    env:
      PROJECT_ROOT: ~/code
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: copy docker-compose and nginx
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          source: "docker-compose.yaml, nginx/default.conf"
          target: ${{ env.PROJECT_ROOT }}
      - name: Create envfile
          uses: SpicyPizza/create-envfile@v1
          with:
            envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
            envkey_POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            envkey_POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            envkey_DB_HOST: "db"
            envkey_DB_PORT: "5432"
            directory: ${{ env.PROJECT_ROOT }}
            file_name: .env
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ env.PROJECT_ROOT }}
            sudo apt-get update -y
            sudo apt-get remove docker docker-engine docker.io -y
            sudo apt install docker.io docker-compose -y
            sudo systemctl start docker
            sudo docker pull izmdi/foodgram
            sudo docker-compose down -v
            sudo docker-compose up -d
            sudo docker-compose exec -T web python manage.py migrate --noinput

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!
